name: Alexandria
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Alexandria:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Ubuntu 24.04 GCC",
            os: ubuntu-24.04,
            compiler: g++,
            comp: gcc,
            shell: 'bash {0}'
          }
        - {
            name: "Windows 2022 GCC",
            os: windows-2022,
            compiler: g++,
            comp: mingw,
            msys_sys: 'mingw64',
            msys_env: 'x86_64-gcc',
            shell: 'msys2 {0}'
          }
    defaults:
      run:
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download required linux packages
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install g++
          sudo apt update
          sudo apt install expect valgrind g++-multilib qemu-user

      - name: Install windows make
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.config.msys_sys}}
          install: mingw-w64-${{matrix.config.msys_env}} make git expect

      - name: download net
        run: curl -sOL https://github.com/PGG106/Alexandria-networks/releases/latest/download/nn.net

      - name: make
        if: runner.os == 'Linux'
        run: make build=debug EVALFILE=nn.net -j

      - name: make build windows
        if: runner.os == 'Windows'
        run: make build=release EVALFILE=nn.net -j

      - name: Bench
        run: |
          ./Alexandria* bench


